// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyZM9q1lnhe4-FK4H3qzzlX0ewID8VY8',
    appId: '1:366447619053:web:51d9e5a7cce42679add5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    authDomain: 'chat-app-3de74.firebaseapp.com',
    storageBucket: 'chat-app-3de74.firebasestorage.app',
    measurementId: 'G-9LFWTPN96B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQbpxpFwgfXeaS-oTEvORl3KI7ibpeDY',
    appId: '1:366447619053:android:cf1e413718d66378add5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    storageBucket: 'chat-app-3de74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_DzaDdFp2VVMWWzf1Cea1-mR2b2i9SY',
    appId: '1:366447619053:ios:2658987ebcd60aadadd5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    storageBucket: 'chat-app-3de74.firebasestorage.app',
    iosBundleId: 'com.example.rolesphereMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_DzaDdFp2VVMWWzf1Cea1-mR2b2i9SY',
    appId: '1:366447619053:ios:2658987ebcd60aadadd5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    storageBucket: 'chat-app-3de74.firebasestorage.app',
    iosBundleId: 'com.example.rolesphereMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApyZM9q1lnhe4-FK4H3qzzlX0ewID8VY8',
    appId: '1:366447619053:web:b53d8dac77070fdfadd5e4',
    messagingSenderId: '366447619053',
    projectId: 'chat-app-3de74',
    authDomain: 'chat-app-3de74.firebaseapp.com',
    storageBucket: 'chat-app-3de74.firebasestorage.app',
    measurementId: 'G-YVK9NFV0VJ',
  );
}
